name: tests
on:
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: make init

      - name: Build documentation with strict mode
        run: make test
